name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: pulse_mates_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable pnpm
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint check
        run: pnpm lint:check

      - name: Format check
        run: pnpm format:check

      - name: TypeScript check
        run: pnpm --filter server tsc --noEmit

      - name: Setup database
        env:
          DATABASE_URL: mysql://root:root@localhost:3306/pulse_mates_test
        run: |
          pnpm --filter server db:generate
          pnpm --filter server db:migrate

      - name: Run server tests
        env:
          DATABASE_URL: mysql://root:root@localhost:3306/pulse_mates_test
          NODE_ENV: test
        run: pnpm --filter server test

      - name: Run mobile tests
        run: pnpm --filter mobile test --watchAll=false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable pnpm
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build server
        run: pnpm --filter server build

      - name: Build mobile (expo)
        run: pnpm --filter mobile expo export

      - name: Upload server build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: apps/server/dist/

      - name: Upload mobile build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mobile-build
          path: apps/mobile/dist/
